### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by processwired** [BernhardBaumrock/PageListSelectUnselectButton#1]
Very nice module!
In order to be able to translate the two strings, an additional underscore is missing:
`var confirmtext = '<?php echo __("click again to confirm"); ?>';
var unselecttext = '<?php echo __("unselect"); ?>';`

**Comment by processwired** [comment]
I noticed that the unselect button is not displayed if the page field is part of a repeater setup.

**Comment by BernhardBaumrock** [comment]
thank you for reporting those issues pwired! i will look at it asap but i am quite busy right now.

**Comment by BernhardBaumrock** [comment]
ajax fields were not supported. added support for ajax loaded fields - that includes repeaters in the new devns branch
