### ISSUE TITLE
Call to undefined function __()

### ISSUE THREAD

**Issue by incognitoms** [BernhardBaumrock/PageListSelectUnselectButton#2]
This is an indispensable module for me - thumbs up and many thanks for it! 

I recently updated one of my PW installs for testing purposes to 3.0.58 and faced the following issue when trying to call the backend:
`Call to undefined function __() (Line 47 in  [...]/site/assets/cache/FileCompiler/site/modules/PageListSelectUnselectButton/PageListSelectUnselectButton.module) `

**Comment by BernhardBaumrock** [comment]
hi @incognitoms 
maybe you want to use https://processwire.com/talk/topic/13389-adminonsteroids/ instead of my module? it has the same functionality and works with pw3 and looks even nicer ;)

**Comment by incognitoms** [comment]
Ah ok, I see... AdminOnSteroids brings in some complexity I would like to avoid, because every feature (if needed or not) is also a potential source for failure (.yes, your guess is right, I'm a fanboy of small, easy to maintain one-trick-ponies ;-)

**Comment by BernhardBaumrock** [comment]
i'm sure tpr would not mind if you take only the code for the unselect. should not be a complex task :)

**Comment by incognitoms** [comment]
For sure :) Thanks, Bernhard
